# Generated by Django 5.2.3 on 2025-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='poll_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='dr_form',
            field=models.FileField(default='Unknown', upload_to='dr_forms/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(default='Unknown', upload_to='photos/'),
        ),
    ]
