# Generated by Django 5.2.3 on 2025-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_report_location_report_poll_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='vote_count',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=100),
        ),
    ]
