# Generated by Django 5.2.3 on 2025-06-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_report_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_passports/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='Candidate', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='Candidate', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='vote_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
