# Generated by Django 5.2.3 on 2025-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_report_spoilt_vote_report_valid_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('late_open', 'Late Opening'), ('missing_materials', 'Missing Materials'), ('voter_intimidation', 'Voter Intimidation'), ('ballot_stuffing', 'Ballot Stuffing'), ('technical_issue', 'Technical Issue'), ('other', 'Other')], default='other', max_length=50)),
                ('photo', models.ImageField(upload_to='incident_photos/')),
                ('dr_form', models.FileField(upload_to='incident_forms/')),
                ('comment', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('poll_name', models.CharField(max_length=255)),
            ],
        ),
    ]
