# Generated by Django 5.2.3 on 2025-06-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
    ]
