# Generated by Django 5.2.3 on 2025-06-24 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_incident_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
