# Generated by Django 5.2.3 on 2025-06-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_incident_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='dr_form',
        ),
    ]
