# Generated by Django 5.2.3 on 2025-06-26 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_alter_incident_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
    ]
