# Generated by Django 5.2.3 on 2025-06-26 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_agent_active_incidents_agent_reports_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('constituency', models.CharField(max_length=100)),
                ('registered_voters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_voters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.candidate')),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.pollingstation')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.region')),
            ],
            options={
                'verbose_name_plural': 'Result Summaries',
            },
        ),
        migrations.CreateModel(
            name='VoteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_votes', models.IntegerField(default=0)),
                ('spoilt_votes', models.IntegerField(default=0)),
                ('candidate_votes', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vote_reports/')),
                ('dr_form', models.FileField(upload_to='dr_forms/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.pollingstation')),
            ],
        ),
    ]
