# Generated by Django 5.2.3 on 2025-06-26 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_pollingstation_region_resultsummary_votereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingstation',
            name='registered_voters',
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='total_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='pollingstation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='agent.pollingstation'),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='constituency',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='votereport',
            name='polling_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votereports', to='agent.pollingstation'),
        ),
    ]
