# Generated by Django 5.2.3 on 2025-06-27 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_remove_pollingstation_registered_voters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.RemoveField(
            model_name='drform',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='panicalert',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='report',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='voterturnout',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='active_incidents',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='reports_submitted',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='location',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='poll_name',
        ),
        migrations.RemoveField(
            model_name='pollingstation',
            name='total_voters',
        ),
        migrations.RemoveField(
            model_name='region',
            name='pollingstation',
        ),
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='constituency',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(default='Independent', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_symbol',
            field=models.ImageField(blank=True, null=True, upload_to='party_symbols/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='polling_station',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.pollingstation'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='registered_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_nin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agent.candidate'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='Agent', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='agent.agent'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('late_open', 'Late Opening'), ('missing_materials', 'Missing Materials'), ('voter_intimidation', 'Voter Intimidation'), ('ballot_stuffing', 'Ballot Stuffing'), ('technical_issue', 'Technical Issue'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='constituency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='votereport',
            name='polling_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.pollingstation'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DRForm',
        ),
        migrations.DeleteModel(
            name='PanicAlert',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='VoterTurnout',
        ),
    ]
