# Generated by Django 5.2.3 on 2025-06-27 01:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_remove_device_user_remove_drform_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='DRforms/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('polling_station', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.pollingstation')),
            ],
        ),
    ]
