# Generated by Django 5.2.3 on 2025-06-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votereport',
            old_name='polling_station',
            new_name='poll_name',
        ),
        migrations.RenameField(
            model_name='votereport',
            old_name='candidate_votes',
            new_name='spoilt_vote',
        ),
        migrations.RenameField(
            model_name='votereport',
            old_name='spoilt_votes',
            new_name='valid_vote',
        ),
        migrations.RenameField(
            model_name='votereport',
            old_name='valid_votes',
            new_name='vote_count',
        ),
    ]
