# Generated by Django 5.2.3 on 2025-06-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_alter_votereport_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votereport',
            name='poll_name',
            field=models.CharField(default='Polling Station', max_length=200),
        ),
    ]
