# Generated by Django 5.2.3 on 2025-06-27 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_alter_votereport_poll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votereport',
            name='poll_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.pollingstation'),
        ),
    ]
