# Generated by Django 5.2.3 on 2025-06-27 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_alter_votereport_poll_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='agent.agent'),
        ),
        migrations.AlterField(
            model_name='resultsummary',
            name='polling_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pollingstation', to='agent.pollingstation'),
        ),
        migrations.AlterField(
            model_name='votereport',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_report', to='agent.agent'),
        ),
    ]
