# Generated by Django 5.2.3 on 2025-06-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0022_report_agent_alter_resultsummary_polling_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='agent.agent'),
        ),
    ]
