# Generated by Django 5.2.3 on 2025-06-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0023_alter_report_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsummary',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_summaries', to='agent.agent'),
        ),
    ]
