# Generated by Django 5.2.3 on 2025-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0024_resultsummary_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='votereport',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
