# Generated by Django 5.2.3 on 2025-06-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0025_report_location_votereport_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
