# Generated by Django 5.2.3 on 2025-06-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0026_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votereport',
            name='poll_name',
            field=models.CharField(max_length=200),
        ),
    ]
