# Generated by Django 5.2.3 on 2025-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0027_alter_votereport_poll_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='polling_station',
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
