# Generated by Django 5.2.3 on 2025-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0028_remove_incident_polling_station_incident_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
