# Generated by Django 5.2.3 on 2025-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0029_incident_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='agents/'),
        ),
    ]
